Change autotools test harnesses into configure generated files
- Enables the configure options for locating service components
  to be passed to test scripts.

Signed-off-by: Christopher M. Cantalupo <christopher.m.cantalupo@intel.com>

diff --git a/test/geopm_test.sh.in b/test/geopm_test.sh.in
--- a/test/geopm_test.sh.in
+++ b/test/geopm_test.sh.in
@@ -30,19 +30,55 @@
 #  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
 
+unset GEOPM_PMPI_CTL
+unset GEOPM_POLICY
+unset GEOPM_REPORT
+unset GEOPM_TRACE
+
 test_name=$(basename $0)
-test_dir=$(dirname $0)
-obj_dir=$(readlink -f ${test_dir}/../../..)
+obj_dir=@abs_top_builddir@
+test_dir=${obj_dir}/test
 lib_path=${obj_dir}/.libs
-real_path=$(dirname $(readlink -f $0))
-top_dir=$(readlink -f ${real_path}/../..)
+exec_path=${obj_dir}/test/.libs
+xml_dir=${test_dir}
+run_test=true
 
-test_class=$(echo ${test_name} | awk -F. '{print $1}')
-scripts_dir=${top_dir}/scripts
-lib_dir=${obj_dir}/.libs
-export PYTHONPATH=${scripts_dir}:${PYTHONPATH}
-export LD_LIBRARY_PATH=${lib_dir}:${LD_LIBRARY_PATH}
 
-# PYTHON is expected to be set when running make check. However, the default
-# value may be used when invoking this script directly from the command line.
-"${PYTHON:-python3}" ${scripts_dir}/test/${test_class}.py --verbose ${test_name} >& ${test_dir}/${test_name}.log
+export LD_LIBRARY_PATH=${lib_path}:@GEOPMD_LIBDIR@:${obj_dir}/openmp/lib:${LD_LIBRARY_PATH}
+
+if [[ ${GTEST_XML_DIR} ]]; then
+    xml_dir=${GTEST_XML_DIR}
+fi
+err=0
+
+# Check for crc32 intrinsic support before running ProfileTable tests
+if [[ ${test_name} =~ ^ProfileTable ]]; then
+    if  ! ./examples/geopm_platform_supported crc32; then
+        echo "Warning: _mm_crc32_u64 intrisic not supported."
+        run_test=false
+    fi
+fi
+
+if [ "${run_test}" == "true" ]; then
+    exec_name=geopm_test
+    if [[ ${test_name} =~ ^MPIInterface ]]; then
+        exec_name=geopm_mpi_test_api
+    fi
+    log_file=${test_dir}/${test_name}.log
+    ${exec_path}/${exec_name} \
+        --gtest_filter=${test_name} \
+        --gtest_output=xml:${xml_dir}/${test_name}.xml >& ${log_file}
+    err=$?
+
+    # Parse output log to see if the test actually ran.
+    if (grep -Fq "[==========] Running 0 tests from 0 test cases." ${log_file}); then
+        echo "ERROR: Test ${test_name} does not exist!"
+        err=1
+    fi
+else
+    echo "SKIP: ${test_name}"
+fi
+
+
+
+exit ${err}
