Fix logic for replacing dbus xml
Signed-off-by: Christopher M. Cantalupo <christopher.m.cantalupo@intel.com>

diff --git a/libgeopmd/Makefile.am b/libgeopmd/Makefile.am
--- a/libgeopmd/Makefile.am
+++ b/libgeopmd/Makefile.am
@@ -339,8 +339,13 @@ $(sysfs_cpp_files): gen-src/%.cpp: $(top_srcdir)/json_data/%.json $(top_srcdir)/
 
 io.github.geopm.xml:
 	PYTHONPATH=$(abs_srcdir)/../geopmdpy \
-	    python3 -m geopmdpy.dbus_xml > $@ || \
-	    echo "Warning: Could not import geopmdpy.dbus_xml, will not update io.github.geopm.xml"
+	    python3 -m geopmdpy.dbus_xml > $@-tmp; \
+	if [ $$? -eq 0 ]; then \
+	    mv $@-tmp $@; \
+	else \
+	    echo "Warning: Could not import geopmdpy.dbus_xml, will not update io.github.geopm.xml"; \
+	    rm -f $@-tmp; \
+	fi
 
 # RPM TARGET
 rpm_topdir ?= $(HOME)/rpmbuild
