Fix copying_headers/test-dist so it uses both distribution tarballs
Signed-off-by: Christopher M. Cantalupo <christopher.m.cantalupo@intel.com>

diff --git a/copying_headers/test-dist b/copying_headers/test-dist
--- a/copying_headers/test-dist
+++ b/copying_headers/test-dist
@@ -30,25 +30,69 @@
 #  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 set -e
+set -x
 
-rm -rf test-dist-tmp
+if [ $# == 0 ]; then
+    BASE_BUILD_DIR=$PWD
+    SERVICE_BUILD_DIR=$PWD/service
+elif [ $# == 1 ]; then
+    BASE_BUILD_DIR=$1
+    SERVICE_BUILD_DIR=$1
+else
+    BASE_BUILD_DIR=$1
+    SERVICE_BUILD_DIR=$2
+fi
+
+TMPDIR=$(mktemp -d)
+mkdir -p ${TMPDIR}
+
 rm -f VERSION
 rm -f MANIFEST
+
 ./autogen.sh
 version=$(cat VERSION)
+
 ./copying_headers/test-license
-rm -f geopm-$version.tar.gz
-if [ ! -f Makefile ]; then
-    ./configure --disable-fortran
-fi
-make dist
-mkdir -p test-dist-tmp
-mv geopm-$version.tar.gz test-dist-tmp
-pushd test-dist-tmp
+
+pushd ${BASE_BUILD_DIR}
+    rm -f geopm-$version.tar.gz
+    if [ ! -f Makefile ]; then
+        echo "Error:  No makefile in base directory, run configure" 1>&2 && false
+    fi
+    make dist
+    mv geopm-$version.tar.gz ${TMPDIR}
+popd
+pushd $SERVICE_BUILD_DIR
+    if [ ! -f Makefile ]; then
+        echo "Error:  No makefile in service directory, run configure" 1>&2 && false
+    fi
+    rm -f geopm-service-$version.tar.gz
+    make dist
+    mv geopm-service-$version.tar.gz ${TMPDIR}
+popd
+
+pushd ${TMPDIR}
     tar -xvf geopm-$version.tar.gz
     pushd geopm-$version
+        ALL_MANIFEST="MANIFEST copying_headers/MANIFEST.*"
+        for ff in $ALL_MANIFEST; do
+            nn=$(echo ${ff} | sed 's|MANIFEST|tmp-MANIFEST|')
+            mv ${ff} ${nn}
+            grep -v '^service' ${nn} > ${ff} || true
+        done
+        ./copying_headers/test-license
+        if [ -d service ]; then
+            echo "Error:  The service directory is created by base tarball" 1>&2 && false
+        fi
+        tar xvf ../geopm-service-$version.tar.gz
+        mv geopm-service-$version service
+        for ff in $ALL_MANIFEST; do
+            nn=$(echo ${ff} | sed 's|MANIFEST|tmp-MANIFEST|')
+            mv ${nn} ${ff}
+        done
         ./copying_headers/test-license
     popd
 popd
-rm -rf test-dist-tmp
+
+echo rm -rf ${TMPDIR}
 echo [ PASSED ] geopm v$version distribution contains all files and all files have license headers.
